# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a943345e26220b73f25eca6498865521b556de7c515e8db266168824f04c89d92175d91429381dbeed46f9dd933f422b2492062badb4bd230fb9ede119b527aa

test:
  secret_key_base: 2bbdb8f79f11a61b7c0a95a5dd0e18d8e5136e01b0b9febd07b809ba004b08560a3520005352324fed854db8c1321063358434fb4ec2c17f874318c056f0d8f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
